language: c
compiler:
    - gcc
    - clang
script: cd src/ && cmake . && make
notifications:
    recipients:
        - lwch748@gmail.com
    email:
        on_success: change
        on_failure: always
