language: c
compiler:
    - gcc
    - clang
before_script:
    - sudo apt-get update -q
    - sudo apt-get install zlib1g-dev liblua5.1-0-dev openssl
script: cd src/ && cmake . && make
notifications:
    recipients:
        - lwch748@gmail.com
    email:
        on_success: change
        on_failure: always
